# Generated by Django 2.2.4 on 2019-08-12 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the recipe', max_length=50, verbose_name='title')),
                ('slug', models.SlugField(help_text='Slug created from the title', unique=True, verbose_name='title slug')),
                ('instructions', models.TextField(blank=True, help_text='Instructions of the recipe', max_length=500, verbose_name='description')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Date of creation of the recipe', verbose_name='creation date')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='Date of last modification one of the recipe', verbose_name='update date')),
                ('author', models.ForeignKey(editable=False, help_text='Author of the recipe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recipe',
                'verbose_name_plural': 'recipes',
            },
        ),
    ]
