# Generated by Django 2.2.4 on 2019-08-15 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mushfood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the picture', max_length=50, verbose_name='title')),
                ('hash', models.CharField(editable=False, help_text='File name', max_length=40, unique=True, verbose_name='hash')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Date of creation of the picture', verbose_name='creation date')),
                ('author', models.ForeignKey(editable=False, help_text='Author of the picture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(editable=False, help_text='Slug created from the title', unique=True, verbose_name='title slug'),
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Date of creation of the picture', verbose_name='creation date')),
                ('image', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_image', to='mushfood.Image')),
                ('recipe', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_image', to='mushfood.Recipe')),
            ],
            options={
                'verbose_name': 'recipe-image',
                'verbose_name_plural': 'recipe-images',
            },
        ),
    ]
