# Generated by Django 2.2.4 on 2019-08-18 15:03

from django.db import migrations, models

from mushfood.utils.model_utils import hash_directory_path


class Migration(migrations.Migration):
  dependencies = [
    ('mushfood', '0003_auto_20190818_1606'),
  ]

  operations = [
    migrations.AlterField(
      model_name='recipeimage',
      name='image',
      field=models.ImageField(editable=False, upload_to=hash_directory_path),
    ),
    migrations.DeleteModel(
      name='Image',
    ),
  ]
