# Generated by Django 2.2.4 on 2019-08-21 21:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mushfood.utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mushfood', '0005_auto_20190820_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the ingredient', max_length=50, verbose_name='name')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Date of creation of the ingredient', verbose_name='creation date')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='Date of last modification one of the ingredient', verbose_name='update date')),
                ('author', models.ForeignKey(editable=False, help_text='Creator of the ingredient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ingredient',
                'verbose_name_plural': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the measurement unit', max_length=50, verbose_name='name')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Date of creation of the measurement unit', verbose_name='creation date')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='Date of last modification one of the measurement unit', verbose_name='update date')),
            ],
            options={
                'verbose_name': 'measurement-unit',
                'verbose_name_plural': 'measurement-units',
            },
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Date of creation of the measurement unit', verbose_name='creation date')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='Date of last modification one of the measurement unit', verbose_name='update date')),
                ('ingredient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='mushfood.Ingredient')),
                ('measurement_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_quantity', to='mushfood.MeasurementUnit')),
            ],
            options={
                'verbose_name': 'ingredient-quantity',
                'verbose_name_plural': 'ingredient-quantities',
            },
        ),
        migrations.CreateModel(
            name='IngredientImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(editable=False, upload_to=mushfood.utils.model_utils.hash_directory_path)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Date of creation of the picture', verbose_name='creation date')),
                ('ingredient', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_image', to='mushfood.Ingredient')),
            ],
            options={
                'verbose_name': 'ingredient-image',
                'verbose_name_plural': 'ingredient-images',
            },
        ),
    ]
