# Generated by Django 3.2.13 on 2023-03-16 12:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mushfood', '0006_ingredient_ingredientimage_ingredientquantity_measurementunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Name of the account', max_length=50, verbose_name='user name')),
                ('first_name', models.CharField(blank=True, help_text='First name of the user', max_length=50, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, help_text='Last name of the user', max_length=50, null=True, verbose_name='last name')),
                ('email', models.CharField(help_text='Email of the user', max_length=50, verbose_name='email')),
                ('reason', models.TextField(help_text='The registration request reason', verbose_name='reason')),
                ('is_rejected', models.BooleanField(default=False, help_text='True if the registration request is rejected', verbose_name='is rejected')),
                ('logical_delete', models.BooleanField(default=False, help_text='True if the registration request is closed', verbose_name='logical delete')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Date of creation of the registration request', verbose_name='creation date')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='Date of last modification of the registration request', verbose_name='update date')),
            ],
            options={
                'verbose_name': 'registration',
                'verbose_name_plural': 'registrations',
            },
        ),
        migrations.AddField(
            model_name='ingredientimage',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='Date of last modification one of the picture', verbose_name='update date'),
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_quantity', to='mushfood.recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementunit',
            name='is_ignorable',
            field=models.BooleanField(default=False, help_text=' Can the measurement unit be ignored', verbose_name='is ignorable'),
        ),
        migrations.AddField(
            model_name='measurementunit',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short name of the measurement unit', max_length=50, null=True, verbose_name='short name'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='inspiration',
            field=models.TextField(blank=True, help_text='Inspiration of the recipe', null=True, verbose_name='inspiration'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='logical_delete',
            field=models.BooleanField(default=False, help_text='True if the recipe is deleted.', verbose_name='logical delete'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='portions',
            field=models.PositiveIntegerField(default=1, help_text='Number of portion this recipe provide', verbose_name='portions'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='variant_of',
            field=models.ForeignKey(help_text='Variant of the recipe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant', to='mushfood.recipe'),
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='Date of last modification one of the picture', verbose_name='update date'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredientimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='mushfood.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='measurementunit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions of the recipe', verbose_name='instructions'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the category', max_length=50, verbose_name='name')),
                ('recipes', models.ManyToManyField(blank=True, to='mushfood.Recipe')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
