# Generated by Django 3.2.13 on 2023-03-26 20:26

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('mushfood', '0008_ingredientquantity_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='rank',
            field=models.PositiveIntegerField(default=0, help_text='Rank of the Ingredient in the recipe', verbose_name='rank'),
        ),
        migrations.CreateModel(
            name='IngredientGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', help_text='Title of the ingredient group', max_length=30, verbose_name='title')),
                ('rank', models.PositiveIntegerField(default=0, help_text='Rank of the ingredient group in the recipe', verbose_name='rank')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Date of creation of the ingredient group', verbose_name='creation date')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='Date of last modification one of the ingredient group', verbose_name='update date')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_group', to='mushfood.recipe')),
            ],
            options={
                'verbose_name': 'ingredient-group',
                'verbose_name_plural': 'ingredient-groups',
            },
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='ingredient_group',
            field=models.ForeignKey(null=True,on_delete=django.db.models.deletion.CASCADE, related_name='group_quantity', to='mushfood.ingredientgroup'),
            preserve_default=False,
        ),
    ]
