# Generated by Django 3.2.13 on 2023-03-26 21:21

from django.db import migrations, models
import django.db.models.deletion

def create_ingredient_group(apps, schema_editor):
    IngredientGroup = apps.get_model('mushfood', 'IngredientGroup')
    IngredientQuantity = apps.get_model('mushfood', 'IngredientQuantity')
    Recipe = apps.get_model('mushfood', 'Recipe')
    for recipe in Recipe.objects.all():
        ingredientGroup = IngredientGroup()
        ingredientGroup.recipe = recipe
        ingredientGroup.save()
        for ingredientQuantity in IngredientQuantity.objects.filter(recipe__id=recipe.id).all():
            ingredientQuantity.ingredient_group = ingredientGroup
            ingredientQuantity.save()

class Migration(migrations.Migration):

    dependencies = [
        ('mushfood', '0009_auto_20230326_2226'),
    ]

    operations = [
        migrations.RunPython(create_ingredient_group),
        migrations.RemoveField(
            model_name='ingredientquantity',
            name='recipe',
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='ingredient_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_quantity', to='mushfood.ingredientgroup'),
        ),
    ]
